# Generated by Django 3.1.2 on 2020-11-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capture', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TweetCapture',
        ),
    ]
